version: '3.8'

services:
  # Serviço da API Node.js
  api:
    build: .
    container_name: cafenataverna-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/cafenataverna-db
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - taverna-network
    volumes:
      - ./src:/app/src
      - /app/node_modules

  # Serviço do MongoDB
  mongodb:
    image: mongo:7
    container_name: cafenataverna-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=cafenataverna-db
    volumes:
      - cafenataverna_data:/data/db
      - cafenataverna_config:/data/configdb
    networks:
      - taverna-network

networks:
  taverna-network:
    driver: bridge

volumes:
  cafenataverna_data:
    driver: local
  cafenataverna_config:
    driver: local